In [1]:
import re
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from pandas import DataFrame
import collections
from datetime import datetime
import sys
from sklearn import preprocessing
from sklearn.metrics import mean_squared_error, r2_score
import csv
from collections import defaultdict

In [2]:
from __future__ import division
from sklearn import datasets
from sklearn.cluster import KMeans
import sklearn.metrics as sm
from sklearn.metrics import accuracy_score
from sklearn import linear_model
from sklearn import tree
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split as tts
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor

In [3]:
data = pd.read_csv("C:/Users/barnesll/Documents/Python/Jupyter/psAveTest.csv", engine='python')

In [4]:
df = pd.DataFrame(data)
df

CB-ISEA Refined Common Name     Refined Command Name  \
0    MARITIME/EXPEDITIONARY C2              GCCS-J              THIRD FLEET   
1    MARITIME/EXPEDITIONARY C2              GCCS-M                GREEN BAY   
2    MARITIME/EXPEDITIONARY C2              GCCS-M                   CARNEY   
3    MARITIME/EXPEDITIONARY C2              GCCS-M                  SAMPSON   
4    MARITIME/EXPEDITIONARY C2              GCCS-M                ANCHORAGE   
5    MARITIME/EXPEDITIONARY C2              GCCS-M         BONHOMME RICHARD   
6    MARITIME/EXPEDITIONARY C2              GCCS-M                 PINCKNEY   
7    MARITIME/EXPEDITIONARY C2              GCCS-M              BUNKER HILL   
8    MARITIME/EXPEDITIONARY C2              GCCS-M       GABRIELLE GIFFORDS   
9    MARITIME/EXPEDITIONARY C2              GCCS-M                 SSC LANT   
10   MARITIME/EXPEDITIONARY C2              GCCS-M                 PORTLAND   
11   MARITIME/EXPEDITIONARY C2              GCCS-M                 ANTIETAM   
12   MARITIME/EXPEDITIONARY C2              GCCS-M                    STOUT   
13   MARITIME/EXPEDITIONARY C2              GCCS-M            MOUNT WHITNEY   
14   MARITIME/EXPEDITIONARY C2              GCCS-M               LEYTE GULF   
15   MARITIME/EXPEDITIONARY C2              GCCS-M                   PORTER   
16   MARITIME/EXPEDITIONARY C2              GCCS-M                   MUSTIN   
17   MARITIME/EXPEDITIONARY C2              GCCS-M                  PATRIOT   
18   MARITIME/EXPEDITIONARY C2              GCCS-M                    NITZE   
19   MARITIME/EXPEDITIONARY C2              GCCS-M                    CHIEF   
20   MARITIME/EXPEDITIONARY C2              GCCS-M                 IWO JIMA   
21   MARITIME/EXPEDITIONARY C2              GCCS-M                 GONZALEZ   
22   MARITIME/EXPEDITIONARY C2              GCCS-M                 SPRUANCE   
23   MARITIME/EXPEDITIONARY C2              GCCS-M            JOHN P MURTHA   
24   MARITIME/EXPEDITIONARY C2              GCCS-M                   SHILOH   
25   MARITIME/EXPEDITIONARY C2              GCCS-M                 COLUMBIA   
26   MARITIME/EXPEDITIONARY C2              GCCS-M                LAKE ERIE   
27   MARITIME/EXPEDITIONARY C2              GCCS-M          GEORGE H W BUSH   
28   MARITIME/EXPEDITIONARY C2              GCCS-M                     COLE   
29   MARITIME/EXPEDITIONARY C2              GCCS-M                SAN DIEGO   
..                         ...                 ...                      ...   
330               APPLICATIONS               NTCSS           MICHAEL MURPHY   
331               APPLICATIONS               NTCSS                    MASON   
332               APPLICATIONS               NTCSS          JOHN PAUL JONES   
333               APPLICATIONS               NTCSS                 COMSTOCK   
334               APPLICATIONS               NTCSS            RONALD REAGAN   
335               APPLICATIONS               NTCSS           RAFAEL PERALTA   
336               APPLICATIONS               NTCSS                   O'KANE   
337               APPLICATIONS               NTCSS             OSCAR AUSTIN   
338               APPLICATIONS               NTCSS                    BOXER   
339               APPLICATIONS               NTCSS                     ROSS   
340               APPLICATIONS               NTCSS               CHUNG-HOON   
341               APPLICATIONS               NTCSS                 RUSHMORE   
342               APPLICATIONS               NTCSS               BLUE RIDGE   
343               APPLICATIONS               NTCSS             FORT MCHENRY   
344               APPLICATIONS               NTCSS      WINSTON S CHURCHILL   
345               APPLICATIONS               NTCSS               GERMANTOWN   
346               APPLICATIONS               NTCSS             PEARL HARBOR   
347               APPLICATIONS               NTCSS                 CHAMPION   
348               APPLICATIONS               NTCSS                 DEXTRO

In [5]:
df2 = df.dropna(axis=0, how='any')
print(df2.shape)
df2

(360, 6)


CB-ISEA Refined Common Name     Refined Command Name  \
0    MARITIME/EXPEDITIONARY C2              GCCS-J              THIRD FLEET   
1    MARITIME/EXPEDITIONARY C2              GCCS-M                GREEN BAY   
2    MARITIME/EXPEDITIONARY C2              GCCS-M                   CARNEY   
3    MARITIME/EXPEDITIONARY C2              GCCS-M                  SAMPSON   
4    MARITIME/EXPEDITIONARY C2              GCCS-M                ANCHORAGE   
5    MARITIME/EXPEDITIONARY C2              GCCS-M         BONHOMME RICHARD   
6    MARITIME/EXPEDITIONARY C2              GCCS-M                 PINCKNEY   
7    MARITIME/EXPEDITIONARY C2              GCCS-M              BUNKER HILL   
8    MARITIME/EXPEDITIONARY C2              GCCS-M       GABRIELLE GIFFORDS   
9    MARITIME/EXPEDITIONARY C2              GCCS-M                 SSC LANT   
10   MARITIME/EXPEDITIONARY C2              GCCS-M                 PORTLAND   
11   MARITIME/EXPEDITIONARY C2              GCCS-M                 ANTIETAM   
12   MARITIME/EXPEDITIONARY C2              GCCS-M                    STOUT   
13   MARITIME/EXPEDITIONARY C2              GCCS-M            MOUNT WHITNEY   
14   MARITIME/EXPEDITIONARY C2              GCCS-M               LEYTE GULF   
15   MARITIME/EXPEDITIONARY C2              GCCS-M                   PORTER   
16   MARITIME/EXPEDITIONARY C2              GCCS-M                   MUSTIN   
17   MARITIME/EXPEDITIONARY C2              GCCS-M                  PATRIOT   
18   MARITIME/EXPEDITIONARY C2              GCCS-M                    NITZE   
19   MARITIME/EXPEDITIONARY C2              GCCS-M                    CHIEF   
20   MARITIME/EXPEDITIONARY C2              GCCS-M                 IWO JIMA   
21   MARITIME/EXPEDITIONARY C2              GCCS-M                 GONZALEZ   
22   MARITIME/EXPEDITIONARY C2              GCCS-M                 SPRUANCE   
23   MARITIME/EXPEDITIONARY C2              GCCS-M            JOHN P MURTHA   
24   MARITIME/EXPEDITIONARY C2              GCCS-M                   SHILOH   
25   MARITIME/EXPEDITIONARY C2              GCCS-M                 COLUMBIA   
26   MARITIME/EXPEDITIONARY C2              GCCS-M                LAKE ERIE   
27   MARITIME/EXPEDITIONARY C2              GCCS-M          GEORGE H W BUSH   
28   MARITIME/EXPEDITIONARY C2              GCCS-M                     COLE   
29   MARITIME/EXPEDITIONARY C2              GCCS-M                SAN DIEGO   
..                         ...                 ...                      ...   
330               APPLICATIONS               NTCSS           MICHAEL MURPHY   
331               APPLICATIONS               NTCSS                    MASON   
332               APPLICATIONS               NTCSS          JOHN PAUL JONES   
333               APPLICATIONS               NTCSS                 COMSTOCK   
334               APPLICATIONS               NTCSS            RONALD REAGAN   
335               APPLICATIONS               NTCSS           RAFAEL PERALTA   
336               APPLICATIONS               NTCSS                   O'KANE   
337               APPLICATIONS               NTCSS             OSCAR AUSTIN   
338               APPLICATIONS               NTCSS                    BOXER   
339               APPLICATIONS               NTCSS                     ROSS   
340               APPLICATIONS               NTCSS               CHUNG-HOON   
341               APPLICATIONS               NTCSS                 RUSHMORE   
342               APPLICATIONS               NTCSS               BLUE RIDGE   
343               APPLICATIONS               NTCSS             FORT MCHENRY   
344               APPLICATIONS               NTCSS      WINSTON S CHURCHILL   
345               APPLICATIONS               NTCSS               GERMANTOWN   
346               APPLICATIONS               NTCSS             PEARL HARBOR   
347               APPLICATIONS               NTCSS                 CHAMPION   
348               APPLICATIONS               NTCSS                 DEXTRO

In [6]:
cbisea = df2['CB-ISEA']
for column1 in cbisea:             #data.columns
    if data['CB-ISEA'].dtype == type(object):
        le = preprocessing.LabelEncoder()
        data['CB-ISEA'] = le.fit_transform(data['CB-ISEA'].astype(str))

In [7]:
common_names = df2['Refined Common Name']
for column2 in common_names:        #data.columns
    if data['Refined Common Name'].dtype == type(object):
        le = preprocessing.LabelEncoder()
        data['Refined Common Name'] = le.fit_transform(data['Refined Common Name'].astype(str))

In [8]:
command_names = df2['Refined Command Name']
for column3 in command_names:      #data.columns
    if data['Refined Command Name'].dtype == type(object):
        le = preprocessing.LabelEncoder()
        data['Refined Command Name'] = le.fit_transform(data['Refined Command Name'].astype(str))

In [9]:
df

CB-ISEA  Refined Common Name  Refined Command Name  Count  Total Days  \
0          2                    8                   168      1         125   
1          2                    9                    52      2           8   
2          2                    9                    20      1           7   
3          2                    9                   147      3         230   
4          2                    9                     3      1           2   
5          2                    9                    14      1           8   
6          2                    9                   131      1          70   
7          2                    9                    17      5         241   
8          2                    9                    46      1           2   
9          2                    9                   158      1           3   
10         2                    9                   135      1           1   
11         2                    9                     4      3         118   
12         2                    9                   164      1           1   
13         2                    9                   100      5          64   
14         2                    9                    80      1           2   
15         2                    9                   134      1           8   
16         2                    9                   109      1           0   
17         2                    9                   127      1          11   
18         2                    9                   120      1           2   
19         2                    9                    25      2          10   
20         2                    9                    65      3         104   
21         2                    9                    51      1           0   
22         2                    9                   157      1          10   
23         2                    9                    69      1           6   
24         2                    9                   154      2         117   
25         2                    9                    29      1         228   
26         2                    9                    77      4           6   
27         2                    9                    47      2          26   
28         2                    9                    27      1         118   
29         2                    9                   148      1           0   
..       ...                  ...                   ...    ...         ...   
330        0                   10                    94      4          45   
331        0                   10                    88      1          37   
332        0                   10                    70      2          15   
333        0                   10                    30      6          90   
334        0                   10                   142      3          45   
335        0                   10                   139      2          30   
336        0                   10                   123      1          15   
337        0                   10                   125      2          59   
338        0                   10                    15      3          30   
339        0                   10                   144      1           0   
340        0                   10                    26      4          60   
341        0                   10                   145      3          45   
342        0                   10                    13      2          22   
343        0                   10                    45      2          26   
344        0                   10                   182      3         147   
345        0                   10                    48      1          15   
346        0                   10                   129      1          15   
347        0                   10                    22      4          60   
348        0                   10                    36      1          61   
349        0               

In [10]:
df2 = df.dropna(axis=0, how='any')
print(df2.shape)
df2

(360, 6)


CB-ISEA  Refined Common Name  Refined Command Name  Count  Total Days  \
0          2                    8                   168      1         125   
1          2                    9                    52      2           8   
2          2                    9                    20      1           7   
3          2                    9                   147      3         230   
4          2                    9                     3      1           2   
5          2                    9                    14      1           8   
6          2                    9                   131      1          70   
7          2                    9                    17      5         241   
8          2                    9                    46      1           2   
9          2                    9                   158      1           3   
10         2                    9                   135      1           1   
11         2                    9                     4      3         118   
12         2                    9                   164      1           1   
13         2                    9                   100      5          64   
14         2                    9                    80      1           2   
15         2                    9                   134      1           8   
16         2                    9                   109      1           0   
17         2                    9                   127      1          11   
18         2                    9                   120      1           2   
19         2                    9                    25      2          10   
20         2                    9                    65      3         104   
21         2                    9                    51      1           0   
22         2                    9                   157      1          10   
23         2                    9                    69      1           6   
24         2                    9                   154      2         117   
25         2                    9                    29      1         228   
26         2                    9                    77      4           6   
27         2                    9                    47      2          26   
28         2                    9                    27      1         118   
29         2                    9                   148      1           0   
..       ...                  ...                   ...    ...         ...   
330        0                   10                    94      4          45   
331        0                   10                    88      1          37   
332        0                   10                    70      2          15   
333        0                   10                    30      6          90   
334        0                   10                   142      3          45   
335        0                   10                   139      2          30   
336        0                   10                   123      1          15   
337        0                   10                   125      2          59   
338        0                   10                    15      3          30   
339        0                   10                   144      1           0   
340        0                   10                    26      4          60   
341        0                   10                   145      3          45   
342        0                   10                    13      2          22   
343        0                   10                    45      2          26   
344        0                   10                   182      3         147   
345        0                   10                    48      1          15   
346        0                   10                   129      1          15   
347        0                   10                    22      4          60   
348        0                   10                    36      1          61   
349        0               

In [11]:
df3 = df2.drop(['Count', 'Total Days'], axis=1)
df3
df3.to_csv("orangefile.csv")

In [12]:
df4 = df3.drop(['Average Lifetime'], axis=1)
df4

CB-ISEA  Refined Common Name  Refined Command Name
0          2                    8                   168
1          2                    9                    52
2          2                    9                    20
3          2                    9                   147
4          2                    9                     3
5          2                    9                    14
6          2                    9                   131
7          2                    9                    17
8          2                    9                    46
9          2                    9                   158
10         2                    9                   135
11         2                    9                     4
12         2                    9                   164
13         2                    9                   100
14         2                    9                    80
15         2                    9                   134
16         2                    9                   109
17         2                    9                   127
18         2                    9                   120
19         2                    9                    25
20         2                    9                    65
21         2                    9                    51
22         2                    9                   157
23         2                    9                    69
24         2                    9                   154
25         2                    9                    29
26         2                    9                    77
27         2                    9                    47
28         2                    9                    27
29         2                    9                   148
..       ...                  ...                   ...
330        0                   10                    94
331        0                   10                    88
332        0                   10                    70
333        0                   10                    30
334        0                   10                   142
335        0                   10                   139
336        0                   10                   123
337        0                   10                   125
338        0                   10                    15
339        0                   10                   144
340        0                   10                    26
341        0                   10                   145
342        0                   10                    13
343        0                   10                    45
344        0                   10                   182
345        0                   10                    48
346        0                   10                   129
347        0                   10                    22
348        0                   10                    36
349        0                   10                    83
350        0                   10                    93
351        0                   10                   119
352        0                   10                   159
353        0                   10                    58
354        0                   10                   175
355        0                   10                   121
356        0                   10                   178
357        0                   10                   156
358        0                   10                     2
359        0                   10                    54

[360 rows x 3 columns]

In [13]:
df4.columns[0:]
psTix_array = np.array(df4[0:])
#psTix_array = df4.as_matrix(columns=df4.columns[0:]) # as_matrix will be removed in future version of numpy
print(psTix_array)

[[  2   8 168]
 [  2   9  52]
 [  2   9  20]
 ...
 [  0  10 156]
 [  0  10   2]
 [  0  10  54]]


In [14]:
#Examples

# Each CB-ISEA will be assigned an unique identifier
#CB-ISEA:
#Application - 0
#Tactical Data Links - 13
#TACNET - 7

# Each Refined Common Name will be assigned an unique identifier
#Common Name:
#MFOM - 3
#TCDL - 5
#LMMT - 10
#CDLS - 11

# Each Refined Command Name will be assigned an unique identifier
#Command Name:
#SSC LANT - 1
#SSC PAC - 5
#Third Fleet - 4
#Ronald Reagan - 12

In [15]:
life_array = np.array(df3['Average Lifetime'], dtype=int)
print(life_array)

[125   4   7  76   2   8  70  48   2   3   1  39   1  12   2   8   0  11
   2   5  34   0  10   6  58 228   1  13 118   0  12   0 104   5   4   3
   3   4  75  78  74   3   7  14  42  60   4   3  86   9   5   0   3   6
   5  11  14 168  37  92   4  63   0   2   2   4  17  14  46   1   8   4
  28  25   3  70   3   7 100   4   2  18   2   8   3   2  30  22  13  40
  14  69  17   7  27  14   6   7  28  22  59  56  28  33  14  24  12  27
  56  24   2  17  14   9  20  14  60  34  35  60   5  15  15   0  10   6
  26   4   6   0  46   5   1   5  14  22   0   0   0  11  19   7   4   7
   7   0   7   0   0   0   4   4   2   4   0   3   5   7   7   0   0   1
   4  21  15   9   0   7   0   0   0   8   0  13   0   3   0  12   9  15
   9   0   1   8  20  10   0  10  45  45  10  21  31  16  25  40  26 135
  42   8  21  25  23  68   3  27  38   6  36  19  14   7  16  11   0 109
   0   0   3  30   7 107   8   2   0   1   2   1   0   0   0   0   0   0
   6   0 363   4   0   0   0   0   1   2   0   0   

In [16]:
# [Incident Ticket Features: CB-ISEA, Common Name, Command]
#features = [[0, 3, 1], [13, 5, 5], [13, 10, 4], [7, 11, 12]]
features = psTix_array

In [17]:
# Average days to complete ticket
#labels = [80, 60, 25, 40]
labels = life_array

In [18]:
# Create classifier (Machine Learning Algorithms)
#clf = tree.DecisionTreeClassifier()    # Decision Tree Algorithm
#clf = RandomForestClassifier()    # Random Forest Classifier Algorithm
#clf = svm.svc()    # Support Vector Machine Algorithm
clf = RandomForestRegressor()
clf = clf.fit(features, labels)

C:\ProgramData\Anaconda3\envs\py37\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [19]:
# Prediction based off given data:
predictions = clf.predict(psTix_array)  #clf.predict([[3, 13, 219], [3, 14, 69], [4, 18, 4], [5, 19, 76]]) # should return [125, 4, 0, 0]
#predictions = clf.predict([[13, 5, 5], [7, 11, 12], [13, 10, 4], [0, 3, 1]])
print(predictions)

[6.540e+01 3.200e+00 9.000e+00 5.400e+01 5.700e+00 6.000e+00 5.660e+01
 3.450e+01 2.100e+00 5.100e+00 1.110e+01 2.420e+01 1.200e+00 7.600e+00
 1.140e+01 1.390e+01 1.200e+00 1.290e+01 3.400e+00 4.370e+01 3.200e+01
 2.300e+00 8.600e+00 1.070e+01 4.600e+01 1.540e+02 3.200e+00 1.080e+01
 9.140e+01 0.000e+00 2.020e+01 8.000e-01 7.250e+01 4.700e+00 1.280e+01
 2.800e+00 1.130e+01 4.100e+00 2.700e+01 4.880e+01 4.460e+01 4.000e+00
 1.820e+01 1.660e+01 4.580e+01 3.420e+01 3.600e+00 2.700e+00 6.750e+01
 5.500e+00 4.070e+01 1.500e+01 6.900e+00 5.100e+00 7.830e+01 1.420e+01
 3.020e+01 1.207e+02 3.750e+01 5.680e+01 1.530e+01 4.290e+01 2.000e+00
 1.600e+00 8.900e+00 1.430e+01 1.500e+01 9.600e+00 4.180e+01 8.000e+00
 1.770e+01 1.710e+01 4.000e+01 2.710e+01 1.050e+01 4.430e+01 1.330e+01
 1.480e+01 6.320e+01 3.500e+00 7.300e+00 1.030e+01 5.200e+00 1.370e+01
 4.500e+00 2.500e+00 1.740e+01 1.290e+01 1.050e+01 4.120e+01 1.040e+01
 5.250e+01 2.080e+01 1.760e+01 2.190e+01 1.800e+01 2.540e+01 1.510e+01
 2.630

In [20]:
score = 0
#test_labels = life_array    #[[5, 19, 76], [4, 18, 4], [3, 13, 219], [3, 14, 69]]
for i in range(len(predictions)):
    if np.any(predictions[i]) == np.any(labels[i]):
        score += 1
print((score/len(predictions)) * 100)

87.77777777777777


In [21]:
#list(le.inverse_transform([42]))  # Returns Commands/Ships and indexes 0 - 248

In [22]:
mean_squared_error(life_array, predictions) ** (1/2)

13.566474200108967

In [23]:
clf.score(features, labels)

0.8296357538274493